//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int ID { get; set; }
        public Nullable<int> Doctor { get; set; }
        public Nullable<int> Patient { get; set; }
        public Nullable<System.DateTime> DateOf { get; set; }
        public Nullable<System.TimeSpan> TimeOf { get; set; }
        public Nullable<bool> Sign { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
